create table "COLOR_LOOKUP" (
    "COLOR_ID"number generated by default on null as identity,
    "COLOR"   varchar2(4000 byte) not null,
    constraint "COLOR_LOOKUP_PK" primary key ("COLOR_ID")
);

insert into "COLOR_LOOKUP" ("COLOR")
select distinct "COLOR"
from "PRODUCTS"
where "COLOR" is not null;

alter table "PRODUCTS" add "COLOR_ID" number;

update "PRODUCTS" x
set "COLOR_ID" = (select "COLOR_ID" from "COLOR_LOOKUP" where "COLOR" = x."COLOR");

alter table "PRODUCTS" drop column "COLOR";

alter table "PRODUCTS"
add constraint "PRODUCTS_COLOR_FK"
foreign key ("COLOR_ID")
references "COLOR_LOOKUP"("COLOR_ID");